// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzL1QF8z0BFAfw4G_SOFqp2uU1DSyzVdk',
    appId: '1:795117756667:web:0f77defa6e408bd410905e',
    messagingSenderId: '795117756667',
    projectId: 'skillup-groupe32',
    authDomain: 'skillup-groupe32.firebaseapp.com',
    storageBucket: 'skillup-groupe32.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtOKfyYiDCLV1iJcZ0DYRQSJkO1IyAgNM',
    appId: '1:795117756667:android:244d1fcee9966a0310905e',
    messagingSenderId: '795117756667',
    projectId: 'skillup-groupe32',
    storageBucket: 'skillup-groupe32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0uezL0Rszl1LG7t1CGZyh-Bzp29MjcU',
    appId: '1:795117756667:ios:8a35ce89ee7d33b210905e',
    messagingSenderId: '795117756667',
    projectId: 'skillup-groupe32',
    storageBucket: 'skillup-groupe32.firebasestorage.app',
    iosBundleId: 'com.groupe32.skillup.skillup',
  );
}
